Update the delete user script

diff --git a/scripting/02 b/scripting/02
--- a/scripting/02
+++ b/scripting/02
@@ -1,14 +1,24 @@
 #!/bin/bash
 
-USERINPUT=$1
-ONLINE="$(who | awk '{print $1}' | grep -o ^"$USERINPUT"$)"
+userinput=$1
+online="$(who | awk '{print $1}' | grep -o ^"$userinput"$)"
+# Use this line if you want to delete any non system user
+# regardless of whether they are online or not.
+# You may want to remove the killall aswell if you use this.
+# online="$(grep -o ^"$userinput" /etc/passwd)"
 
-if [ "$ONLINE" == "$USERINPUT" ]
+if [ "$EUID" -ne 0 ]
 then
-	echo "The user \"$USERINPUT\" is logged in, logging them out then deleting their account."
-	killall -u "$USERINPUT"
-	deluser --remove-home "$USERINPUT"
-	echo "\"$USERINPUT\" has been logged out and their account deleted."
+	echo "Script error: this script needs to be run with root priviledges."
+	exit 1
+fi
+
+if [ "$userinput" == "$online" ]
+then
+	echo "The user \"$userinput\" is logged in, logging them out then deleting their account."
+	killall -u "$userinput"
+	deluser --remove-home "$userinput"
+	echo "\"$userinput\" has been logged out and their account deleted."
 else
-	echo "The user \"$USERINPUT\" is not logged in."
+	echo "The user \"$userinput\" is not logged in."
 fi
